version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: ecolocator_mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecolocator_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: